---
title: 'Statistics 218: Labs Outline'
output:
  pdf_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Lab 2:  Visualization

## Topics:
Reading, interpreting, comparing, and knowing when to use...
*	Histograms
*	Dot plots
*	Box plots
*	Bar graphs
*	[Pie Charts - omitted in R section]
*	Side-by-Side box plots
*	Side-by-Side bar graphs
*	Stacked bar graphs
*	Scatter plots
*	Line plots

## Dataset:  Titanic (abbreviated)

## R Skills: 
*	Creating all the above in ggplot
*	Grouping and facetting
*	Optional bells and whistles for plotting

## Assignment:  Titanic final report

## Additional Resources:
* RStudio Cheatsheets: ggplot2
* Colors pdf
* Link some tutorials?


# Lab 3:  Random Variables, Categorical/discrete distributions

## Topics:
*	Random variables:  samples and populations, statistics and parameters
*	Frequency tables
*	Probability
*	The Binomial Distribution
*	Quantifying evidence: baby chi-square?

## Dataset:  Election data? 

## Skills: 
*	[review] Counting up categoricals
*	Making a frequency table from data: `reshape` stuff
*	Using `pbinom()` and `qbinom()`
*	Simulation?  `rbinom()`

## Assignment:  Hmmmm.....

## Additional Resources
* Applets!

# Lab 4:  Hypothesis Testing

## Topics:
*⦁	Hypothesis test general principles
*	1-sample prop test
* very gentle intro to confidence interval for $p$
*	Chi-Square Test

## Dataset:  same as lab 3 ideally.  Election data?

## R Skills: 
*	[review] making frequency tables
*	[review] `pbinom()`, `qbinom()`
*	`pchisq()`, `qchisq()`, maybe?  probably.
*	`prop.test()`
*	`chisq.test()`

## Assignment:  Final report on [biodata].

## Additional Resources:
* Applets
* Real-world chi-square study abstracts and such


# Lab 5:  Densities, the CLT

## Topics:
*	Density curves
*	The Uniform distribution
*	The Normal distribution
*	CLT
*	Normal approximation to Binomial

## Dataset:  basketball??? hmmmmm I don't love it....

## R Skills: 
*	`runif()`, `punif()`, `qunif()`
*	`rnorm()`, `dnorm()`, `qnorm()`, `pnorm()`
*	Curves in `ggplot`
*	simulation....?
*	qq plots

## Assignment:  Not bball.  Make them do a different dataset.

# Lab 6: t-tests and confidence intervals

## Topics:
* one-sample t-test
* two-sample t-test
* Confidence intervals for $\mu$ and $\mu_1 - \mu_2$

## Dataset: wine?

## R Skills: 
* `t.test()`
* Maybe conf int calculations?

## Assignment: wine?  options?

## Additional Resources:
* Real world abstracts

# Lab 7: ANOVA

## Topics:
* ANOVA
* Multiple testing, Tukey HSD

## Dataset: bodwins

## R Skills: 
* [review] Side-by-side boxplots
* `anova()`, `lm()`, `aov()`
* `tukeyHSD()`

## Assignment: your family or similar

## Additional Resources:
* Real world abstracts

# Lab 8: Regression

## Topics:
* Linear models
* Least squares and residuals
* Residual plots
* Transformation of variables?

## Dataset: kellys

## R Skills: 
* `lm()`
* [review] scatterplots
* Adding model to scatterplot
* Prediction
* Plotting residuals (hmmm why does it suck in ggplot.  maybe worth building by hand)

## Assignment: your choice of names stuff

## Additional Resources


# Lab 9: Final project



