---
title: "Lab 3 Grading Guide"
output:
  html_document: 
    css: style.css
  pdf_document: default
---

## The Dataset [(13 points)]{style="float:right"}

* Did the student use `head()` and/or `summary()` to examine the data?  [(3)]{style="float:right"}
* Did the student use class vocabulary to describe some of the variables? [(5)]{style="float:right"}
* Did the student discuss the dataset, mentioning at least one of: sampling method, number of observations, experimental vs observational?  [(5)]{style="float:right"}

## Checking Normality? [(11 points)]{style="float:right"}

* Is there a histogram plot?  [(5)]{style="float:right"}
* Does the histogram include a density curve? [(3)]{style="float:right"}
* Did the student discuss whether the histogram looked Normal?  [(3)]{style="float:right"}

## Normal Probabilities and Evidence [(31 points)]{style="float:right"}

* Correct mean and sd calculated (must show code, e.g. using `summarize_at`. [(6, 3 each)]{style="float:right"}
* Correct `pnorm` calculation to find probability. [(5)]{style="float:right"}
* Correct number of points for SB, with code (`filter()`) [(5)]{style="float:right"}
* Correct percentage of games below 52 points (`filter()` or `count()`) (no credit for 5.8% again; ok if they have 4.55%) [(5)]{style="float:right"}
* Discussion of similarity of actual percent vs. calculated Normal probability. [(5)]{style="float:right"}
* Discussion of how unusual the game was. [(5)]{style="float:right"}

## Samples [(8 points)]{style="float:right"}

* Is the probability correctly calculated using `pnorm()`?  (Answers will vary because of different samples.  -3 points for using `sd = 13.1`) [(5)]{style="float:right"}
* Is the probability correctly interpreted in discussion?  [(3)]{style="float:right"}

## Cal Poly [(8 points)]{style="float:right"}

* Is `filter()` used correctly to create the dataset?  [(3)]{style="float:right"}
* Is the probability correctly calculated using `pnorm()`?  (-3 points for using `sd = 13.1`) [(5)]{style="float:right"}
* Is the probability correctly interpreted in discussion?  [(3)]{style="float:right"}

## Home vs. Away? [(29 points)]{style="float:right"}

* Is there a plot that reasonably addresses the research question? [(8)]{style="float:right"}
* Is there a calculation using `pnorm()` or `pbinom()`? [(8)]{style="float:right"}
* Does the discussion accurately interpret the plot(s) and the probability? [(5)]{style="float:right"}
* Does the analysis make a convincing case to answer the research question? [(8)]{style="float:right"}