---
title: "Lab 5 Grading Guide"
output:
  html_document: 
    css: style.css
  pdf_document: default
---

## The Dataset [(8 points)]{style="float:right"}

* Did the student use `head()` and/or `summary()` to examine the data?  [(3)]{style="float:right"}
* Did the student use class vocabulary to discuss the dataset? [(5)]{style="float:right"}

## Potato-ness by treatment [(24 points)]{style="float:right"}

* Did the student perform an appropriate test for parts 1 and 3?  [(8, 4 each)]{style="float:right"}
* Did the student correctly interpret the p-value and vie a real-world conclusion for the tests in parts 1 and 3?  [(8, 4 each)]{style="float:right"}
* Did the student make a histogram in part 2?  [(4)]{style="float:right"}
* Did the student reasonably discuss the qqplot and histogram in part 2?  [(4)]{style="float:right"}

## Potato or not [(20 points)]{style="float:right"}

* Did the student use `count()` to count potato-y fries (numbers will vary)? [(5)]{style="float:right"}
* Did the student correctly identify the distribution in part 2? [(5)]{style="float:right"}
* Did the student use `pbinom()` to find the correct probability (numbers will vary)? [(5)]{style="float:right"}
* Did the student reasonably discuss the probability and make a real-world conclusion? [(5)]{style="float:right"}

## Grassy or Painty [(26 points)]{style="float:right"}

* Did the student perform an appropriate test for parts 1 and 3?  [(8, 4 each)]{style="float:right"}
* Did the student correctly interpret the p-value and vie a real-world conclusion for the tests in parts 1 and 3?  [(8, 4 each)]{style="float:right"}
* Did the student make a qq plot and histogram in part 2?  [(8, 4 each)]{style="float:right"}
* Did the student reasonably discuss the qqplot and histogram in part 2?  [(4)]{style="float:right"}

## Rancid [(30 points)]{style="float:right"}

* Is there a hypothesis test that reasonably addresses the research question? [(10)]{style="float:right"}
* Is there a plot that reasonably addresses the research question? [(8)]{style="float:right"}
* Is there a discussion that interprets the plot and test correctly, and makes a good case for the research question? [(12)]{style="float:right"} 